name: Coverbot | Code Coverage
description: Quickly determine code coverage.

branding: 
  icon: check-circle
  color: blue

inputs:
  file: 
    description: location of json file
    required: true
  coverbot_api_key: 
    description: Coverbot Token
    required: true
  github_token: 
    description: GitHub Token
    required: true
  subdirectory: 
    description: If your app is in a subdirectory, specify it here
    required: false
outputs:
  covered: 
    description: Number of lines covered
  relevant: 
    description: Number of lines considered relevant
  percentage: 
    description: The coverage percentage
runs:
  using: 'node16'
  main: 'index.js'