name: Check Example Files
on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: read
  statuses: write

jobs:
  excoveralls:
    name: elixir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./
        with:
          format: elixir
          file: example_coverage_files/excoveralls.json
          coverbot_api_key: ${{ secrets.COVERBOT_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  go:
    name: go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          format: go
          file: example_coverage_files/go.out
          coverbot_api_key: ${{ secrets.COVERBOT_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  lcov:
    name: lcov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          format: lcov
          file: example_coverage_files/lcov.info
          coverbot_api_key: ${{ secrets.COVERBOT_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  ruby:
    name: ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          format: ruby
          file: example_coverage_files/simplecov.json
          coverbot_api_key: ${{ secrets.COVERBOT_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}